name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка компилятора
      run: sudo apt-get install g++ -y

    - name: Компиляция проекта
      run: g++ -std=c++17 MathFunctions.cpp main.cpp -o test_app

    - name: Запуск тестов
      run: ./test_app
